# Generated by Django 5.2.3 on 2025-07-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flota", "0021_modelovehiculo_rendimiento_optimo_kml_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordendetrabajo",
            name="conclusion_prueba_de_ruta",
            field=models.TextField(
                blank=True,
                help_text="Conclusiones y observaciones de la prueba de ruta.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ordendetrabajo",
            name="prueba_de_ruta_realizada",
            field=models.BooleanField(
                default=False,
                help_text="Marcar si se realizó una prueba de ruta para validar los síntomas.",
            ),
        ),
    ]
