# Generated by Django 5.2.3 on 2025-07-16 11:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flota", "0022_ordendetrabajo_conclusion_prueba_de_ruta_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Neumatico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dot",
                    models.CharField(
                        help_text="Código DOT único del neumático.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
                (
                    "medida",
                    models.CharField(help_text="Ej: 295/80R22.5", max_length=50),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EN_BODEGA", "En Bodega"),
                            ("MONTADO", "Montado"),
                            ("EN_RECAUCHAJE", "En Recauchaje"),
                            ("DESECHADO", "Desechado"),
                        ],
                        default="EN_BODEGA",
                        max_length=20,
                    ),
                ),
                ("fecha_compra", models.DateField()),
                ("costo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "profundidad_surco_actual_mm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Profundidad del surco en milímetros.",
                        max_digits=5,
                    ),
                ),
                (
                    "profundidad_surco_limite_mm",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        help_text="Límite de desgaste para alertas.",
                        max_digits=5,
                    ),
                ),
                ("kilometraje_acumulado", models.PositiveIntegerField(default=0)),
                (
                    "posicion_actual",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Delantera Izquierda, Trasera Derecha Interior",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "vehiculo_actual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="neumaticos_montados",
                        to="flota.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Neumático",
                "verbose_name_plural": "Neumáticos",
                "ordering": ["marca", "modelo"],
            },
        ),
        migrations.CreateModel(
            name="InspeccionNeumatico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inspeccion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "presion_psi",
                    models.PositiveIntegerField(help_text="Presión medida en PSI."),
                ),
                (
                    "profundidad_surco_mm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Profundidad del surco medida en milímetros.",
                        max_digits=5,
                    ),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "neumatico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspecciones",
                        to="flota.neumatico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspección de Neumático",
                "verbose_name_plural": "Inspecciones de Neumáticos",
                "ordering": ["-fecha_inspeccion"],
            },
        ),
        migrations.CreateModel(
            name="HistorialMontaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[("MONTAJE", "Montaje"), ("DESMONTAJE", "Desmontaje")],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("kilometraje_vehiculo", models.PositiveIntegerField()),
                (
                    "posicion",
                    models.CharField(
                        help_text="Posición en la que se montó/desmontó el neumático.",
                        max_length=50,
                    ),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "orden_de_trabajo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="montajes_asociados",
                        to="flota.ordendetrabajo",
                    ),
                ),
                (
                    "usuario_responsable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_montajes_vehiculo",
                        to="flota.vehiculo",
                    ),
                ),
                (
                    "neumatico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_montajes",
                        to="flota.neumatico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Montaje",
                "verbose_name_plural": "Historiales de Montaje",
                "ordering": ["-fecha"],
            },
        ),
    ]
