# Generated by Django 5.2.3 on 2025-07-16 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flota", "0023_neumatico_inspeccionneumatico_historialmontaje"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ordendetrabajo",
            name="neumatico_asociado",
            field=models.ForeignKey(
                blank=True,
                help_text="Neumático principal afectado en esta OT, si aplica.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordenes_de_trabajo",
                to="flota.neumatico",
            ),
        ),
        migrations.CreateModel(
            name="ChecklistInspeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inspeccion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("kilometraje", models.PositiveIntegerField()),
                (
                    "luces",
                    models.BooleanField(default=False, verbose_name="Estado de Luces"),
                ),
                (
                    "niveles_fluidos",
                    models.BooleanField(
                        default=False,
                        verbose_name="Niveles de Fluidos (Aceite, Refrigerante)",
                    ),
                ),
                (
                    "presion_neumaticos",
                    models.BooleanField(
                        default=False, verbose_name="Presión de Neumáticos"
                    ),
                ),
                (
                    "frenos",
                    models.BooleanField(
                        default=False, verbose_name="Sistema de Frenos"
                    ),
                ),
                (
                    "elementos_seguridad",
                    models.BooleanField(
                        default=False,
                        verbose_name="Elementos de Seguridad (Extintor, Botiquín)",
                    ),
                ),
                (
                    "aprobado",
                    models.BooleanField(
                        default=False, help_text="Se marca si todos los ítems están OK."
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "conductor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklists_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklists",
                        to="flota.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist de Inspección",
                "verbose_name_plural": "Checklists de Inspección",
                "ordering": ["-fecha_inspeccion"],
            },
        ),
    ]
