# Generated by Django 5.2.3 on 2025-07-16 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flota", "0024_ordendetrabajo_neumatico_asociado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenciaOT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("archivo", models.FileField(upload_to="evidencias_ot/")),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "orden_de_trabajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="flota.ordendetrabajo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuario que subió la evidencia.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidencia de OT",
                "verbose_name_plural": "Evidencias de OT",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
