# Generated by Django 5.2.3 on 2025-07-16 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flota", "0025_evidenciaot"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReglaAlerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "metrica",
                    models.CharField(
                        choices=[
                            ("COSTO_KM", "Costo por Kilómetro"),
                            ("CONSUMO_COMBUSTIBLE", "Consumo de Combustible (L/100km)"),
                            ("FRECUENCIA_FALLA", "Frecuencia de Falla (por tipo)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "operador",
                    models.CharField(
                        choices=[
                            ("MAYOR_QUE", "Mayor que"),
                            ("MENOR_QUE", "Menor que"),
                            ("IGUAL_A", "Igual a"),
                        ],
                        max_length=20,
                    ),
                ),
                ("valor_umbral", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "periodo_dias",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Número de días hacia atrás para calcular la métrica.",
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "modelo_vehiculo",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Dejar en blanco para aplicar a todos los modelos.",
                        to="flota.modelovehiculo",
                    ),
                ),
                (
                    "tipo_falla_asociada",
                    models.ForeignKey(
                        blank=True,
                        help_text="Necesario solo si la métrica es 'Frecuencia de Falla'.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flota.tipofalla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de Alerta",
                "verbose_name_plural": "Reglas de Alertas",
            },
        ),
    ]
