# Generated by Django 5.2.3 on 2025-07-17 14:25

from django.db import migrations

def create_nuevos_widgets(apps, schema_editor):
    Widget = apps.get_model('flota', 'Widget')

    NUEVOS_WIDGETS = [
        {
            "nombre": "Tiempo Medio Entre Fallas (MTBF)",
            "descripcion": "Muestra el tiempo promedio (en horas) que un vehículo opera sin fallas.",
            "template_name": "widgets/kpi_mtbf.html"
        },
        {
            "nombre": "Tiempo Medio de Reparación (MTTR)",
            "descripcion": "Muestra el tiempo promedio (en horas) que se tarda en reparar una falla.",
            "template_name": "widgets/kpi_mttr.html"
        },
        {
            "nombre": "Distribución de Costos de Mantenimiento",
            "descripcion": "Un gráfico de dona que muestra el porcentaje de costos de OTs Preventivas vs. Correctivas.",
            "template_name": "widgets/distribucion_costos.html"
        },
    ]

    for widget_data in NUEVOS_WIDGETS:
        Widget.objects.get_or_create(template_name=widget_data['template_name'], defaults=widget_data)


class Migration(migrations.Migration):

    dependencies = [
        ("flota", "0027_seed_widgets"),
    ]

    operations = []
